### ISSUE TITLE
checkpoints doesn't get removed after the player finishes the parkour

### ISSUE THREAD

**Issue by ghost** [CaptainDuck/EnderParkour#1]
everything works fine but the player saved checkpoints doesn't get removed after he finishes the parkour . when he finish the parkour he can come back and fall into the void then he respawns at the last checkpoint he touched . please fix this issue . thank u

**Comment by CaptainDuck** [comment]
Yes, I am aware and working on this issue :D

**Comment by CaptainDuck** [comment]
Hello! This feature has been planned and being worked on, in the mean time, read this [Note](https://github.com/CaptainDuck/EnderParkour#ideas).

Thanks! :D

**Comment by CaptainDuck** [comment]
This feature has now been added :D
